### ISSUE TITLE
Add high level README

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-workflow-examples#11]
This should contain a caveat that the examples should run with flux-core 0.11 and flux-sched 0.7. We should also note when the new execution system w/ resource matching service, we will port the examples to the new services.

**Comment by cmoussa1** [comment]
This issue should be resolved by PR #30: __flux-core 0.11__ and __flux-sched 0.7__ now have their own branch in the `flux-workflow-examples` repository with a top-level README describing each example.

**Comment by cmoussa1** [comment]
This issue should also be resolved by PR #47. **master** now has its own top-level README with links and descriptions of each example.
