### ISSUE TITLE
Updating workflow examples with our new systems

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-workflow-examples#12]
@cmoussa1 and I just discussed to update our workflow examples with the new execution system and graph-based scheduler. Here is what we agreed to do.

1. Fork this repo into flux-framework/flux-workflow-examples.core-v0.11.sched-v0.7 so that users can refer to the current snapshot if they wan to use the older systems.

2. Then, @cmoussa1 starts to update those 10 examples one by one and do a PR for each directly in this repo. 

We believe that this work will help bring @cmoussa1 further up to speed on his banking/account infrastructure design/implementation.

**Comment by dongahn** [comment]
I plan to create a fork tomorrow. If you have a better suggestion for the repo name of the fork, please let us know.

**Comment by grondo** [comment]
Maybe you don't need to fork and can just create a branch. Some of the reasoning behind the v0.11/v0.7 forks of flux-core/flux-sched probably don't apply to a documentation repository. (Then again, creating a fork of a doc project is much simpler, so up to you)

You can refer to the outdated examples branch in the `README.md` of master with a statement like:

**NOTE**:  These examples assume you are running flux-core version >= 0.13 and flux-sched >= 0.8. For older examples based on v0.11/v0.7 please see  https://github.com/flux-framework/flux-workflow-examples/old.

**Comment by SteVwonder** [comment]
Awesome!  Thanks for taking this on @cmoussa1!  One other request while you are going through the examples: can you include a short summary of each example in the top-level README.md like is done in the [RFC](https://github.com/flux-framework/rfc/) repo?  Even if it is just a descriptive title, it should make it easier to find the relevant example from the top-level.

**Comment by dongahn** [comment]
Yeah I like the branch idea better. How about creating a release based on the snapshot as well?

**Comment by dongahn** [comment]
I like @SteVwonder's suggestion as well.

**Comment by cmoussa1** [comment]
This issue should be resolved by PR #40, which was the last PR to update our workflow examples to line up with the new execution system.

**Comment by dongahn** [comment]
Thanks.
