### ISSUE TITLE
example4: 'flux.cpuset' not found when running ensemble.sh

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#17]
When running `./ensemble.sh`, the following error is produced:

```
Jobid: 1
Cmdline:  ["./io-forwarding.lua","12"]
lua: ./R_lite.lua:3: module 'flux.cpuset' not found:
	no field package.preload['flux.cpuset']
	no file '/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.x-20180618/share/lua/5.1/flux/cpuset.lua'
	no file './flux/cpuset.lua'
	no file '/usr/share/lua/5.1/flux/cpuset.lua'
	no file '/usr/share/lua/5.1/flux/cpuset/init.lua'
	no file '/usr/lib64/lua/5.1/flux/cpuset.lua'
	no file '/usr/lib64/lua/5.1/flux/cpuset/init.lua'
	no file '/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.x-20180618/lib/lua/5.1/flux/cpuset.so'
	no file './flux/cpuset.so'
	no file '/usr/lib64/lua/5.1/flux/cpuset.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
	no module 'flux.cpuset' in file '/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.x-20180618/lib/lua/5.1/flux.so'
stack traceback:
	[C]: in function 'require'
	./R_lite.lua:3: in main chunk
	[C]: ?
Resource: 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dongahn** [comment]
@cmoussa1: Is there a new version installed under /collab/usr/global/tools/flux/toss_3_x86_64_ib which you can try this on also?

@grondo: Did `flux.cpuset` survive throughout all the revisions leading to flux-core-v0.11?

**Comment by cmoussa1** [comment]
Tried running under the following paths, and got the same error:

`/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.11.2-dbg`
`/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.x-20180618`
`/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux4uqp-20181129`

**Comment by dongahn** [comment]
Thanks. 

BTW @StevWonder and I talked to UQP team today. They are now going full speed integrating Flux scheduling into UQP  and I suggest them to look at these examples as their tutorial. 

Once your upgrade to the latest Flux (current masters for core and sched) complete, I will steer them to make use of that version  instead of the old examples.

**Comment by cmoussa1** [comment]
Great! I'll be sure to keep updating/testing the workflow examples so we can continue to clear up any problems we might run into, as well as upload a top-level README with an outline and description of all of the examples (thanks to the suggestion and reminder from PR #15 @SteVwonder!)

**Comment by grondo** [comment]
Sorry, I was offline for a bit. This is a typo in `io-forwarding.lua`. There is no `flux.cpuset` module, instead the script should require `flux.affinity`, of which `cpuset` is a member. Something like:
```lua
local cpuset = require 'flux.affinity'.cpuset
```
Should work.

**Comment by dongahn** [comment]
@cmoussa1: just for a future reference, a typical workflow is to wait until the fix is merged to the upstream repo before closing an issue. Thank you for doing this.

**Comment by cmoussa1** [comment]
Oops, my apologies! will note this for future issues.
