### ISSUE TITLE
example5: flux-module: capp: not found in module search path

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#19]
It looks like the modules `capp` and `ioapp` are not being loaded correctly (or at all), resulting in a hanging execution. Here are my steps of execution:

```
> salloc -N3 -ppdebug
> setenv FLUX_SCHED_OPTIONS "node-excl=true"
> srun --pty --mpi=none -N3 /usr/global/tools/flux/toss_3_x86_64_ib/default/bin/flux start -o,-S,log-filename=out
> make
> flux submit -N 2 -n 2 ./compute.lua 120
> flux submit -N 2 -n 2 ./io-forwarding.lua 120
```

And here's the output after attaching to `./compute.lua` with `flux wreck attach 1`

```
bash-4.2$ flux wreck attach 1                    
flux-module: capp: not found in module search path
Module               Size    Digest  Idle  S  Nodeset
connector-local      1292816 0AFE609    0  R  0
aggregator           1280976 266E167    4  S  0
userdb               1263872 2AEEE1F    4  S  0
resource-hwloc       1285024 D9C4CB3    4  S  0
cron                 1347288 266E939    0  S  0
sched                 469184 E0A40B2    0  S  0
job                  1331936 6C39A05    0  S  0
content-sqlite       1271848 1E84888    0  S  0
barrier              1261984 A751886    4  S  0
kvs                  1694520 BAB9F2A    0  S  0
```

Are there more steps needed after running `make` to link the `capp` and `ioapp` libraries to flux-core?

**Comment by grondo** [comment]
@cmoussa1, try adding the directory to the modules to `FLUX_MODULE_PATH`. E.g. if module was built in the current dir:
```console
$ export FLUX_MODULE_PATH=${FLUX_MODULE_PATH}:$(pwd)
```

**Comment by cmoussa1** [comment]
Thanks, @grondo. Following your suggestion, I was receiving a seg fault when `flux submit`ting `./compute.lua`. After playing around with it some more, I also set the following environment variable before launching the Flux instance:

`export PKG_CONFIG_PATH='/usr/global/tools/flux/toss_3_x86_64_ib/default/lib/pkgconfig'`

This resulted in a successful submission of both jobs, but it seems like the job is hanging when `./compute.lua` is running. Here's the output from attaching to it:

```
bash-4.2$ flux wreck attach 1
Module               Size    Digest  Idle  S  Nodeset
connector-local      1292816 0AFE609    0  R  0
aggregator           1280976 266E167    8  S  0
userdb               1263872 2AEEE1F    8  S  0
resource-hwloc       1285024 D9C4CB3    8  S  0
cron                 1347288 266E939    0  S  0
sched                 469184 E0A40B2    0  S  0
job                  1331936 6C39A05    0  S  0
capp                   13064 A9817AB    0  S  0
content-sqlite       1271848 1E84888    0  S  0
barrier              1261984 A751886    8  S  0
kvs                  1694520 BAB9F2A    0  S  0
salloc: Job 3713138 has exceeded its time limit and its allocation has been revoked.
```

It looks like it's hanging around lines 26-28 in `compute.lua`? I could be wrong though. 

Adding @dongahn in case he might know how to fix this.

**Comment by grondo** [comment]
Interesting `PKG_CONFIG_PATH` shouldn't be used unless running `./configure` in a project.

Do you have the reproducer in a branch I could try out?

**Comment by dongahn** [comment]
@cmoussa1: Let's take a look at this together. Maybe at 4PM today?

**Comment by cmoussa1** [comment]
@grondo I produced this error just from pulling the `workflow-examples` repo on GitHub onto my account on an LC machine and running it as is (I'm sorry if this isn't what you meant by having the reproducer in a branch). 

@dongahn sounds good, see you then.

**Comment by cmoussa1** [comment]
@grondo Also, for reference:

I set `PKG_CONFIG_PATH` based on the workflow posted on [example10](https://github.com/cmoussa1/flux-workflow-examples/tree/example7-update/example10)

**Comment by grondo** [comment]
> I set PKG_CONFIG_PATH based on the workflow posted on [example10].

Ah, thanks. Yeah that is there to support the subsequent call to `make`.

**Comment by cmoussa1** [comment]
The following set of instructions seemed to fix this issue (_note: I would clean the directory and run_ `make` _inside the SLURM allocation every time I walked through this example_):

1. `salloc -N3 -ppdebug`
2. `export PKG_CONFIG_PATH='<flux install path>/lib/pkgconfig/'`
3. `make` 
4. `export FLUX_MODULE_PATH=${FLUX_MODULE_PATH}:$(pwd)`
4. `srun --pty --mpi=none -N3 flux start -o,-S,logfilename=out`

followed by `mini submit`ting the jobs and the rest of the walkthrough.

**Comment by cmoussa1** [comment]
PR #29 and PR #38 have been merged, so I'll close this issue.
