### ISSUE TITLE
discussion: structure of flux-workflow-examples repo with updated examples

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#32]
Opening this ticket to get some feedback on how we should structure this repository with the addition of the new examples according to the latest version of Flux. Currently, the branches for this repo are:
- `master` 
- `flux-core-0.11.flux-sched-0.7`. 

Should we make a new branch `flux-core-0.13.flux-sched-0.7` and add the new examples there?

**Comment by grondo** [comment]
We should keep the new examples on `master` since we don't plan on making any more radical changes to UI or API in the near future. If the need ever arises, we can create a new branch then.

**Comment by cmoussa1** [comment]
Sounds good, thank you! I'll go ahead and close this issue.
