### ISSUE TITLE
Some Example Headers are Inconsistent

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-workflow-examples#48]
Two minor nits:

Example 9 says "Example 10"

Example 2 doesn't have the "Example 2 -" prefix that all of the other examples have

**Comment by SteVwonder** [comment]
Example 2 will be fixed by @cmoussa1's PR #40

**Comment by cmoussa1** [comment]
I'm not sure how to assign this issue to myself, but I will take care of this issue!
