### ISSUE TITLE
re-order examples to reflect increasing depth/complexity

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#55]
The examples should be re-organized to reflect an appropriate order to work through them, maybe from least complex to most complex. Right now, the order in which the examples are placed are the following:

1. launch flux instance, schedule/launch compute and io-forwarding jobs using CLI
2. schedule/launch compute and io-forwarding jobs using the Python bindings
3. use events to synchronize compute and io-forwarding jobs 
4. launch a flux instance and submit one instance of an io-forwarding job and a large number of compute jobs
5. use a Flux Comms module to communicate with job elements
6. launch a large number of `sleep 0` jobs
7. submit job bundles and wait until all jobs complete
8. use KVS Python interface to store user data into KVS
9. attach to a job that receives OS time data from compute jobs
10. submit jobs and wait for them to complete using the flux Python bindings
11. python asynchronous bulk job submission 

I am very open to suggestions on how we might want to re-order the examples; for starters, we could probably place examples 10, 11 after example 7. @SteVwonder had a good suggestion of keeping the data conduit example (9) last, since that is probably the most complex one we have at the moment.

**Comment by cmoussa1** [comment]
Here is a first proposal for re-ordering the examples:

1. (1) launch flux instance, schedule/launch compute and io-forwarding jobs using CLI
2. (2) schedule/launch compute and io-forwarding jobs using the Python bindings
3. (10) submit jobs and wait for them to complete using the flux Python bindings
4. (11) python asynchronous bulk job submission 
5. (7) submit job bundles and wait until all jobs complete
6. (3) use events to synchronize compute and io-forwarding jobs 
7. (8) use KVS Python interface to store user data into KVS
8. (4) launch a flux instance and submit one instance of an io-forwarding job and a large number of compute jobs
9. (6) launch a large number of `sleep 0` jobs
10. (5) use a Flux Comms module to communicate with job elements
11. (9) attach to a job that receives OS time data from compute jobs

The numbers in the parentheses represent the current ordering of the examples in the repo.

**Comment by SteVwonder** [comment]
LGTM!

On a related note, it might be worth tweaking the description of (what is currently) example 7 to emphasize how it is different from (what is currently) example 10.  My suggestion would be something like "submit job bundles, print live job events, and exit when all jobs are complete"

**Comment by cmoussa1** [comment]
Thanks for the suggestion @SteVwonder - I like that description.

**Comment by cmoussa1** [comment]
From a coffee time discussion with @SteVwonder: 

Renaming the directories to reflect the name of the example itself will be a good idea. We could then keep an ordering in the top-level README for which they should be walked through. I'll propose a draft of the renamed directories in this issue thread before I post the actual changes in PR #62.

**Comment by cmoussa1** [comment]
Here's a first draft of the renamed directories:

[partitioning-schedule](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example1)
[direct-submit-RPC](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example2)
[job-submit-wait](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example3)
[job-status-control](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example4)
[synchronize-events](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example5)
[kvs-python-binding](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example6)
[job-ensemble](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example7)
[hierarchical-launching](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example8)
[comms-module](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example9)
[data-conduit](https://github.com/cmoussa1/flux-workflow-examples/tree/reorder-examples/example10)

I basically just abbreviated the titles of the examples to rename the dirs, but if there are any other suggestions I'm absolutely open to changing them!

**Comment by SteVwonder** [comment]
LGTM!  My only suggestion would be to tweak the first two.  Maybe something like `job-submit-CLI` and `job-submit-API`?

**Comment by cmoussa1** [comment]
Thanks for your suggestion @SteVwonder, I like that!

Thinking about this a bit more, I'm trying to think about what happens after PR #62 is merged into `master`. None of the hyperlinks will work for the top-level README because they point to `master/example[n]`. Is there a good workaround that I'm not thinking of for avoiding the links being broken until a follow-up PR is submitted to fix those links?

**Comment by SteVwonder** [comment]
> Is there a good workaround that I'm not thinking of for avoiding the links being broken until a follow-up PR is submitted to fix those links?

I don't think so.  I would go with your latter suggestion (i.e., change the links ahead of time) so that the PR is self-contained and doesn't require two PRs (leaving the master branch in a broken state in between).
