### ISSUE TITLE
bulksubmit.py needs to be updated

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-workflow-examples#66]
This command is slightly broken under the current flux-core master.

https://github.com/flux-framework/flux-workflow-examples/tree/master/async-bulk-job-submit

https://github.com/flux-framework/flux-core/issues/2915#issuecomment-620889771

**Comment by grondo** [comment]
I have it on my list to turn this into a command that we can pull into flux-core. Sorry I have not gotten to it  yet..

**Comment by sfurmanvt** [comment]
This is the change in interface I was talking about during the 6/24/2020 coffee time.

**Comment by cmoussa1** [comment]
Thanks for letting us know @sfurmanvt! PR #68 is currently open and waiting to be approved and merged - however, feel free to take a look at that branch if you want a working example.

**Comment by cmoussa1** [comment]
I think this can be closed now since #68 was merged.
