### ISSUE TITLE
Add a job cancel example 

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#70]
Mentioned in a Slack thread, but it might be nice to add an example demonstrating job cancellation. We currently have an example of cancelling a job in the [tests](https://github.com/flux-framework/flux-core/blob/4d208f24e5133b66ccfa3ff2f61aed3243ab90ef/t/python/t0010-job.py#L179):

```python
def test_15_job_cancel(self):
    self.sleep_jobspec = JobspecV1.from_command(["sleep", "1000"])
    jobid = job.submit(self.fh, self.sleep_jobspec, waitable=True)
    job.cancel(self.fh, jobid)
    fut = job.wait_async(self.fh, jobid=jobid).wait_for(5.0)
    return_id, success, errmsg = fut.get_status()
    self.assertEqual(return_id, jobid)
    self.assertFalse(success)
```

**Comment by cmoussa1** [comment]
Sorry if this is a dumb question. 😅  From the code snippet pasted above, it looks like the job gets submitted, but then immediately cancelled:

```
bash-4.2$ flux jobs -A
    JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
f4EubhNLX moussa1  sleep      CA      1      -        - -
```

Do we also want to include an example of cancelling a job via the command line? Something like the following?

```
$ flux mini submit sleep 1000
f4EubhNLX
$ flux job cancel f4EubhNLX
$ flux jobs -A
    JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
f4EubhNLX moussa1  sleep      CA      1      1   9.044s 0
```

In the second case, the job will run for at least a few seconds before I can type `flux job cancel <jobid>`. Does that matter for the purposes of this example?

**Comment by grondo** [comment]
There may have been an assumption that the workflow examples were mainly targeted at Python examples, but I don't see how a commandline example would hurt, though those may be more appropriate for a "User's Guide" doc.

> Sorry if this is a dumb question. 😅 From the code snippet pasted above, it looks like the job gets submitted, but then immediately cancelled:

Yes, the job is immediately canceled. You can cancel a job that is either in SCHED state (pending) or RUN state (running). You can only signal a job (`flux job kill`) if it is in the RUN state.

(I wonder if we want to add an example of signaling a job if it doesn't already exist)
