### ISSUE TITLE
Where are the example scripts?

### ISSUE THREAD

**Issue by Larofeticus** [flux-framework/flux-workflow-examples#86]
This page 
https://flux-framework.readthedocs.io/projects/flux-workflow-examples/en/latest/job-submit-wait/README.html
contains a text reference to submitter_wait_any.py

There is no link to where that script is located, there is no nearby example explaining or showing what exactly is inside it. It hasn't appeared in the path from a flux install so a person trying out examples with a flux module loaded won't see it that way.

There is also submitter_sliding_window.py and submitter_wait_in_order.py and the same pattern of missing detail on other pages as well.

The example page _about python job API_ doesn't have _any_ python API until the notes at the bottom.

I understand that the example code is (probably?) in the gitlab, but your users aren't going to be browsing or searching in the gitlab and may very well not even know it's there. 

As an example, suppose i am a learning use that wants "submitter_wait_any.py" from the earlier page. I don't see a link to it there, so i put the string "submitter_wait_any" into the docs search. It only returns that same page. I click on the "edit on gitlab" link (already a stretch for user behavior) and search for the same string on the gitlab. That search also finds nothing new.

**Comment by grondo** [comment]
This is a totally valid complaint. I think the initial assumption with flux-workflow-examples was that the user would have the examples repo checked out locally and would follow along that way. I think since then the repos got added to the read-the-docs site, which kind of dissociated the examples text from the examples source.

We should redo the workflow examples in tutorial style with all the code inline, or at least links where you can download and run the examples.

**Comment by dongahn** [comment]
I agree. Thank you for sending your feedback @Larofeticus. It is essential to get this type of feedback at this stage of Flux development. Keep yours coming!

**Comment by grondo** [comment]
And to answer the question in the issue title, all the flux-workflow-example scripts are contained in the repo, e.g. `submitter_wait_any.py` can be found here

https://github.com/flux-framework/flux-workflow-examples/tree/master/job-submit-wait

**Comment by SteVwonder** [comment]
>  I think since then the repos got added to the read-the-docs site, which kind of dissociated the examples text from the examples source.

> We should redo the workflow examples in tutorial style with all the code inline, or at least links where you can download and run the examples.

Agreed.  We have an open issue tracking that particular suggestion #81.  Cross-referencing for future reference.
