### ISSUE TITLE
Example for running on Summit

### ISSUE THREAD

**Issue by kshitij-v-mehta** [flux-framework/flux-workflow-examples#9]
Hello Flux team,
Does Flux run on Summit? If so, would you have some examples for it?

Thanks,
Kshitij Mehta
ORNL

**Comment by dongahn** [comment]
Yes it should run there.

You can either build and install flux-core and flux-sched manually or through spackle and invoke a flux instance using jsrun on a batch allocation. LLNL has a short readme on our confluence wiki for Sierra, I will attach a pdf here when I get to my computer.

Can I ask what is your use case?

**Comment by kshitij-v-mehta** [comment]
*   Can I ask what is your use case?
I wanted to try Flux as an alternative to schedulers such as PBS, Slurm etc.
Also, I am curious to know what the workflow definition will look like for Summit, as Summit has the concept of resource sets instead of the usual total no. of processes, processes-per-node etc.

**Comment by dongahn** [comment]
[SIERRA-UsingFluxtoscheduleandrunjobs-280119-0939-400.pdf](https://github.com/flux-framework/flux-workflow-examples/files/2804167/SIERRA-UsingFluxtoscheduleandrunjobs-280119-0939-400.pdf)

**Comment by dongahn** [comment]
@kshitij-v-mehta: I attached the pdf above. Now that I think about this, installing Flux using our Spack recipe would be the best practice on Summit as you have an additional dependency: "correctly" configured hwloc. @SteVwonder?

Feel free to use this ticket to ask any followup question you might have.

>  I am curious to know what the workflow definition will look like for Summit

If you have an example workflow you want to try on Flux, I am interested in seeing the resource requirements and requests of your workflow as well.

**Comment by kshitij-v-mehta** [comment]
Thanks.
Specifically, my use case is this: use a workflow composition tool (Flux) to create a set of experiments. Each experiment consists of a workflow (simulation + analysis) in which its component applications are  launched together.
Then, submit a bunch of these experiments to Flux and let it manage the job sumission.

For example, I may have an allocation of 100 nodes and a bunch of experiments with varying node requirements. I believe Flux can schedule experiments, monitor them, and keep submitting experiments as experiments complete and resources become available.

Hope that helps. Let me know if you have questions.

**Comment by dongahn** [comment]
@kshitij-v-mehta: Yes. I believe your use cases should be covered well with the current capability. Thank you for the additional explanation!

**Comment by SteVwonder** [comment]
> Installing Flux using our Spack recipe would be the best practice on Summit as you have an additional dependency: "correctly" configured hwloc. 

Yep!  `spack install flux-sched@0.6.0+cuda` should get you a Summit-compatible version.  The `+cuda` builds `hwloc` with cuda support so that Flux can auto-discover the GPUs on the nodes.  The latest release of flux-sched (0.7.0) isn't quite available yet via spack because the PR we have open hasn't been merged yet (https://github.com/spack/spack/pull/10447).  @kshitij-v-mehta, let me know if you have any issues installing via Spack.

**Comment by dongahn** [comment]
@tgamblin and @lee218llnl: any help on our latest Spack PR will be appreciated!

**Comment by tgamblin** [comment]
merged

**Comment by kshitij-v-mehta** [comment]
Not sure if this is the right place to discuss this .. I am curious on how Flux works on supercomputers such as Summit. Do you internally submit jsrun commands, or are you bypassing the system scheduler in some way?

**Comment by dongahn** [comment]
This is one way to use flux. But on such a system, you will get your allocation with lag and use jsrun to launch your flux instance. And then you will submit or launch your jobs in your workflow to that instance. Please look at the pdf I attached there. You should get some idea about how flux can be used in your workflow on Summit.

**Comment by dongahn** [comment]
@kshitij-v-mehta: do you need more from this issue ticket or can I close it?

**Comment by kshitij-v-mehta** [comment]
I don't need more. Please feel free to close it. 
Thanks for your help.

**Comment by dongahn** [comment]
Hopefully you got what you wanted to achieve. Some of us will visit ORNL in March so if you want to meet us, please let us know.
